name: phantom
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  cupertino_icons: ^1.0.6
  #firebase
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.4
  firebase_app_check: ^0.2.2+6
  #state management
  flutter_bloc: ^8.1.5
  #else
  google_fonts: ^6.2.1
  audioplayers: ^6.0.0
  image_picker: ^1.1.1
  flutter_countdown_timer: ^4.1.0
  floating_action_bubble: ^1.1.4
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  syncfusion_flutter_sliders: ^25.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
